### ISSUE TITLE
NoCredentialProviders error

### ISSUE THREAD

**Issue by amitshlo** [appleboy/drone-lambda#4]
Hello,
Thank you creating this plugin, that's exacly what I needed.

When I try to use it I get the follwing error:

```
time="2018-02-11T13:21:56Z" level=info msg="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
time="2018-02-11T13:21:56Z" level=warning msg="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```
(I think those logs should be labeled as errors).

It's possible I'm not using your plugin correctly, I am new to Drone.
My .drone.yml:

```
pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run pack

  deploy-lambda:
    image: appleboy/drone-lambda
    when:
      branch: master
    AWS_ACCESS_KEY_ID: XXX
    AWS_SECRET_ACCESS_KEY: XXX
    FUNCTION_NAME: Lambda-ts
    ZIP_FILE: dist/lambda-ts.zip
```

Thank you!

**Comment by appleboy** [comment]
@amitshlo Please try the following config:

```yaml
  deploy-lambda:
    image: appleboy/drone-lambda
    access_key: xxx
    secret_key: xxx
    function_name: xxx
    zip_file: dist/lambda-ts.zip
    when:
      branch: master
```
